services:
  postgres:
    image: postgres:17
    container_name: blog_notes_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - blog_notes_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  blog_notes_pgdata:
