[package]
name = "blog-server"
version.workspace = true
edition.workspace = true
build = "build.rs"

[[bin]]
name = "blog-server"
path = "src/main.rs"

[dependencies]
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["signal"] }
actix-cors.workspace = true
actix-web = { workspace = true, features = ["macros"] }
argon2.workspace = true
password-hash.workspace = true
dotenvy.workspace = true
jsonwebtoken.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
tonic-build.workspace = true

[dev-dependencies]
serde_urlencoded = "0.7"
